# -*- coding: utf-8 -*-
"""SVMs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SRsF-PaqwxqW3Gk653WDsDsQt9i0qmaT

#Usamos maquinas de vectores cuando tenemos datos con muchas caracteristicas y cuando no hay muchos ya que si no puede tardar demasiado
"""

from sklearn import datasets

datos = datasets.load_breast_cancer(as_frame=True)

datos.frame.head()

datos.frame.info()

datos.frame.isna().sum()

datos.frame.describe()

datos.data.shape

from sklearn.model_selection import train_test_split
x= datos.data
y = datos.target
x_ent, x_pru, y_ent, y_pru = train_test_split(x, y, test_size = .3)

from sklearn import svm
from sklearn import metrics

kernels = ["linear", "rbf", "sigmoid"]
gammas = [1, .01, .001, .0001, .00001]

for kernel in kernels:
  for gamma in gammas:
    modelo = svm.SVC(kernel=kernel, gamma=gamma)
    modelo.fit(x_ent, y_ent)
    predicciones = modelo.predict(x_pru)
    print(f"Kernel: {kernel} - Gamma: {gamma} - Exactitud: ", metrics.accuracy_score(y_pru, predicciones))
    print(f"Kernel: {kernel} - Gamma: {gamma} - Precision: ", metrics.precision_score(y_pru, predicciones))

modelo = svm.SVC(kernel="linear")
modelo.fit(x_ent, y_ent)
predicciones = modelo.predict(x_pru)
print(f"Kernel: {kernel} - Gamma: {gamma} - Exactitud: ", metrics.accuracy_score(y_pru, predicciones))
print(f"Kernel: {kernel} - Gamma: {gamma} - Precision: ", metrics.precision_score(y_pru, predicciones))

from sklearn.metrics import classification_report
print(classification_report(y_pru, predicciones))

